### ISSUE TITLE
On ubuntu Se wont start

### ISSUE THREAD

**Issue by SkyIT** [rglx/SEDS-Setup#17] opened 2015-11-20 11:42 UTC
First i wanna thank you for your scripts, 2nd if u could help me to find out whats problem of my server i ll be gratefull
I have run ur script and everything has done
ubuntu version 14.04.03 lts (64bit)
Im not really good with ubuntu as u can guess.
When i start se server it load but at end shut down for an error exception object
here's log:
http://pastebin.com/UZbQJzL5
config file is imported from my computer
Ty for ur attention :3

Sky

**Comment by goreacraft** [comment] 2015-11-20 14:20
i dont think it works if you have planets on your map.. having same problems here

**Comment by SkyIT** [comment] 2015-11-20 16:50
maybe something missing it ?  dunno any library ?

**Comment by mccorkle** [comment] 2015-11-20 17:31
Hey SkyIT.  I just booted up my server from pre-planets, and even with the update (but no new save file, e.g. no planets in there) it works as expected.  

Not to discourage you, but space engineers is an alpha game and running a dedicated server on ubuntu is an unsupported platform, so getting this up and running isn't for the faint at heart.  If you are ready to get deeper into resolving your problem, read on.  

To diagnose what the problem is, remove all the complexities to your setup:
1) Create a new save game with only the stock asteroids in it (NO planets)
2) make sure your sbc and sbs files (the save game XML data) has no mods
3) turn off drones (its in the sbc file, which you can edit with any text editor)

Now, try and fire up your dedicated server again and see if you get the same error.  If not, add each of those things back in, one at a time, to narrow down which it is.  If you create a save file like above and it still gives you the error, zip up the save file and share a link to that zip as well and I'll test on my ubuntu 14.04.03 LTS server to see if we can narrow down what's causing it.

**Comment by SkyIT** [comment] 2015-11-23 15:29
GOt it  wrong einvorment of wine .. was running 64bit instead of 32
Ty for script

**Closed** 2022-04-13 10:16 UTC
